commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

encyclopedia/urls.py
from django.urls import path

from encyclopedia import util

from . import views


app_name = "encyclopedia"



urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:TITLE>", views.TITLE_, name="title"),
    path("search", views.search, name="search"),
    path("create", views.create, name="create"),
    path("wiki/<str:TITLE>/edit", views.edit, name="edit"),
    path("random",views.random_, name="random")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
import imp
import markdown2
from django.http import HttpResponse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from markdown2 import Markdown
from django.urls import reverse
from django import forms
import random

from . import util

class NewEntyForm(forms.Form):
    title = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)


class EditForm(forms.Form):
    message = forms.CharField(widget=forms.Textarea)

def index(request):
    print(util.list_entries())
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def TITLE_(request, TITLE):
    to_markdown = Markdown()
    entry_title = TITLE
    entry_body =  util.get_entry(TITLE)
    if entry_body == None:
        return render(request, "encyclopedia/error.html", {"message": f"{entry_title} does not Exist"})
    return render(request, "encyclopedia/title.html", {
        "entry": to_markdown.convert(entry_body), "title" : entry_title 
    })

def search(request):
    # 
    if request.method == 'POST':
        # print("inside search")
        s_value = request.POST.get('q')
        #  print(request.POST.get('q'))
        # print(s_value)
        list_ = util.list_entries()
        # print(list_)
        if s_value in list_:
            return TITLE_(request, s_value)
        else:
            list_item = []
            # print(s_value)
            for item in list_:
                # print(item)
                if s_value.upper() in item.upper():
                    # print(item)
                    list_item.append(item)
            return render(request, "encyclopedia/search.html", {"list_item":list_item, "item":s_value})

def create(request):
    if request.method == "POST":
        form = NewEntyForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            message = form.cleaned_data["message"]
            if util.get_entry(title) == None:
                util.save_entry(title, message)
                return TITLE_(request,title)
            else:
                return render(request, "encyclopedia/error.html", {"message": f"{title} Already  Exists", "visit":True, "title":title})
    else:
        return render(request, "encyclopedia/create.html", {"form": NewEntyForm()})
    

def edit(request, TITLE):
    if request.method == "POST":
        form = EditForm(request.POST)
        if form.is_valid():
            message = form.cleaned_data["message"]
            util.save_entry(TITLE, message)
            return TITLE_(request,TITLE)

    entry = util.get_entry(TITLE)
    form = EditForm(initial={
        "message": entry
    })
    
    return render(request, "encyclopedia/edit.html", {"form":form, "title":TITLE})


def random_(request):
    entry_list = util.list_entries()
    random_item = random.choice(entry_list)
    return TITLE_(request,random_item)

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create New Entry
{% endblock %}

{% block body %}
    <h1>Create New Page</h1>

    <form action="{% url 'encyclopedia:create' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
      </form>

{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <h3>Message:</h3>
<form action="{% url 'encyclopedia:edit' title %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
  </form>


{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    "Error"
{% endblock %}

{% block body %}
    <h1>Error</h1>

    <h1>{{message}}</h1>
    {% if visit %}
        <a href="{% url 'encyclopedia:title' title %}"> Edit {{title}}</a>
    {% endif %}
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:title' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' CSS %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="POST">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a> 
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a> 
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search 
{% endblock %}

{% block body %}
    <h1>Search For {{item}} </h1>
    <ul>
        {% for item in list_item %}
            <li><a href="{% url 'encyclopedia:title' item %}"> {{item}} </a></li>
        {% empty %}
            <li>No match for {{item}}</li>
        {% endfor %}
    </ul>
    
{% endblock %}

encyclopedia/templates/encyclopedia/title.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    
    {{ entry|safe }}
    
    <a class="btn btn-primary" href="{% url 'encyclopedia:edit' TITLE=title %}" role="button">Edit</a>

{% endblock %}